name: Kernel Build Workflow

on:
  workflow_dispatch:
    inputs:
      kernelsu_version:
        description: 'KernelSU Version (MKSU, KSU, KSUNEXT)'
        required: true
        default: 'MKSU'
      branch_type:
        description: 'Branch Type (dev, stable)'
        required: true
        default: 'dev'
      branch_suffix:
        description: 'Branch Suffix (e.g., lts, 2024-11, 2025-01)'
        required: true
        default: 'lts'

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Environment
        run: |
          # 清除之前的 PATH 环境变量
          export PATH=$(getconf PATH)
          # 创建 ~/bin 目录并添加到 PATH
          mkdir -p ~/bin
          export PATH=~/bin:$PATH
          # 下载 repo 工具并设置执行权限
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          # 设置全局 Git 配置
          git config --global http.postBuffer 524288000

      - name: Initialize and Sync Repositories
        run: |
          # 初始化 repo，使用 Google 官方仓库地址
          repo init -u https://android.googlesource.com/kernel/manifest -b ${{ github.event.inputs.branch_type }}-${{ github.event.inputs.branch_suffix }}
          repo sync -c --no-tags --fail-fast

      - name: Clone SUSFS4KSU
        run: |
          git clone -b gki-android13-5.15 https://gitlab.com/simonpunk/susfs4ksu.git

      - name: Download and Run Setup Script
        run: |
          # 根据选择的 KernelSU 版本下载并运行脚本
          if [ "${{ github.event.inputs.kernelsu_version }}" == "MKSU" ]; then
            curl -LSs https://raw.githubusercontent.com/ShirkNeko/KernelSU/susfs/kernel/setup.sh | bash -s susfs
          elif [ "${{ github.event.inputs.kernelsu_version }}" == "KSU" ]; then
            curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash -s susfs
          elif [ "${{ github.event.inputs.kernelsu_version }}" == "KSUNEXT" ]; then
            curl -LSs https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh | bash -s next
          else
            echo "Invalid KernelSU version. Using default MKSU."
            curl -LSs https://raw.githubusercontent.com/ShirkNeko/KernelSU/susfs/kernel/setup.sh | bash -s susfs
          fi

      - name: Apply Patches
        run: |
          # 应用补丁
          cd susfs4ksu
          cp ./kernel_patches/* ../
          cd ..
          patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch || true

      - name: Build Kernel
        run: |
          # 根据分支类型选择编译命令
          if [ "${{ github.event.inputs.branch_type }}" == "dev" ]; then
            ./tools/bazel build --config=fast //common:kernel_aarch64_dist
          else
            LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
          fi

      - name: Package AnyKernel3
        run: |
          # 打包 AnyKernel3
          IMAGE_FILE=$(find ./out -name 'Image' -type f)
          if [ -z "$IMAGE_FILE" ]; then
            echo "No Image file found. Exiting."
            exit 1
          fi
          TEMP_DIR=$(mktemp -d)
          unzip AnyKernel3-android13-5.15.zip -d "$TEMP_DIR"
          cp "$IMAGE_FILE" "$TEMP_DIR/"
          cd "$TEMP_DIR"
          zip -r AnyKernel3-${{ github.event.inputs.branch_type }}-${{ github.event.inputs.branch_suffix }}-${{ github.event.inputs.kernelsu_version }}.zip .
          mv *.zip $GITHUB_WORKSPACE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Kernel Build
          path: ${{ github.workspace }}/*.zip
