name: Build susfsd
on:
  push:
    branches: [ "susfs" ]
    paths:
      - '.github/workflows/susfsd.yml'
      - 'userspace/susfsd/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      os:
        required: false
        type: string
        default: self-hosted
jobs:
  build-susfs:
    name: Build userspace susfsd
    runs-on: self-hosted
    env:
      HTTP_PROXY: http://192.168.1.2:7897
      HTTPS_PROXY: http://192.168.1.2:7897
      NO_PROXY: localhost,127.0.0.1,.github.com
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v3
      with:
        ndk: latest
    - name: Set ANDROID_NDK environment variable
      run: |
        echo "ANDROID_NDK=$HOME/android-ndk" >> $GITHUB_ENV
    - name: Build susfsd
      working-directory: ./userspace/susfsd
      run: $ANDROID_NDK/ndk-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: susfsd-aarch64-linux-android
        path: ./userspace/susfsd/libs
    
